services:
  frontend:
    image: sebastian2313025/infraestructura-saavedra:frontend
    container_name: frontend
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    image: sebastian2313025/infraestructura-saavedra:backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./backend:/app/backend
    networks:
      - my-network
    depends_on:
      - db

  db:
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: caferosita
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network


networks:
  my-network:
    driver: bridge

volumes:
  db_data: # Declaración del volumen
